// Mocks generated by Mockito 5.4.0 from annotations
// in plansteria/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i9;

import 'package:dartz/dartz.dart' as _i3;
import 'package:firebase_storage/firebase_storage.dart' as _i6;
import 'package:flutter/material.dart' as _i8;
import 'package:image_picker/image_picker.dart' as _i19;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:plansteria/core/errors/auth_error.dart' as _i11;
import 'package:plansteria/core/errors/chat_error.dart' as _i21;
import 'package:plansteria/core/errors/event_error.dart' as _i17;
import 'package:plansteria/models/chat_response.dart' as _i22;
import 'package:plansteria/models/event.dart' as _i5;
import 'package:plansteria/models/message.dart' as _i23;
import 'package:plansteria/models/user.dart' as _i2;
import 'package:plansteria/services/auth_service.dart' as _i10;
import 'package:plansteria/services/chat_service.dart' as _i20;
import 'package:plansteria/services/event_service.dart' as _i16;
import 'package:plansteria/services/media_service.dart' as _i18;
import 'package:plansteria/services/network_service.dart' as _i13;
import 'package:plansteria/services/open_mail_app_service.dart' as _i15;
import 'package:plansteria/services/secure_storage_service.dart' as _i12;
import 'package:stacked_services/stacked_services.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOption_1<A> extends _i1.SmartFake implements _i3.Option<A> {
  _FakeOption_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSubscription_3<T> extends _i1.SmartFake
    implements _i4.StreamSubscription<T> {
  _FakeStreamSubscription_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvent_4 extends _i1.SmartFake implements _i5.Event {
  _FakeEvent_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReference_5 extends _i1.SmartFake implements _i6.Reference {
  _FakeReference_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i7.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i8.GlobalKey<_i8.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i8.GlobalKey<_i8.NavigatorState>?);
  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i7.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<T?>? navigateWithTransition<T>(
    _i8.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i8.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i7.Transition? transitionClass,
    _i7.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  _i4.Future<T?>? replaceWithTransition<T>(
    _i8.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i8.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i7.Transition? transitionClass,
    _i7.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void popUntil(
    _i8.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i8.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  _i4.Future<T?>? navigateToView<T>(
    _i8.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i8.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i7.Transition? transition,
    _i7.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  _i4.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i8.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  _i4.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  _i4.Future<T?>? clearStackAndShowView<T>(
    _i8.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  _i4.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  _i4.Future<T?>? clearTillFirstAndShowView<T>(
    _i8.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
  @override
  _i4.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i8.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i7.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i7.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<_i7.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i4.Future<_i7.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i4.Future<_i7.SheetResponse<dynamic>?>.value(),
      ) as _i4.Future<_i7.SheetResponse<dynamic>?>);
  @override
  _i4.Future<_i7.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i9.Color? barrierColor = const _i9.Color(2315255808),
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i4.Future<_i7.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.SheetResponse<T>?>.value(),
      ) as _i4.Future<_i7.SheetResponse<T>?>);
  @override
  void completeSheet(_i7.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i7.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i7.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i8.Widget Function(
      _i8.BuildContext,
      _i7.DialogRequest<dynamic>,
      dynamic Function(_i7.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<_i7.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i9.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i9.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i7.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i4.Future<_i7.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i4.Future<_i7.DialogResponse<dynamic>?>.value(),
      ) as _i4.Future<_i7.DialogResponse<dynamic>?>);
  @override
  _i4.Future<_i7.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i9.Color? barrierColor = const _i9.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i4.Future<_i7.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.DialogResponse<T>?>.value(),
      ) as _i4.Future<_i7.DialogResponse<T>?>);
  @override
  _i4.Future<_i7.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    String? confirmationTitle = r'Ok',
    bool? barrierDismissible = false,
    _i7.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #confirmationTitle: confirmationTitle,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i4.Future<_i7.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i4.Future<_i7.DialogResponse<dynamic>?>.value(),
      ) as _i4.Future<_i7.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i7.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i4.Stream<_i2.User> userByIdStream(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #userByIdStream,
          [userId],
        ),
        returnValue: _i4.Stream<_i2.User>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.User>.empty(),
      ) as _i4.Stream<_i2.User>);
  @override
  _i4.Future<_i2.User> getUserById(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.User>);
  @override
  _i4.Future<void> checkAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #checkAuthenticated,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i3.Option<_i3.Either<_i11.AuthError, bool>>>
      checkEmailVerified() => (super.noSuchMethod(
            Invocation.method(
              #checkEmailVerified,
              [],
            ),
            returnValue:
                _i4.Future<_i3.Option<_i3.Either<_i11.AuthError, bool>>>.value(
                    _FakeOption_1<_i3.Either<_i11.AuthError, bool>>(
              this,
              Invocation.method(
                #checkEmailVerified,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i3.Option<_i3.Either<_i11.AuthError, bool>>>.value(
                    _FakeOption_1<_i3.Either<_i11.AuthError, bool>>(
              this,
              Invocation.method(
                #checkEmailVerified,
                [],
              ),
            )),
          ) as _i4.Future<_i3.Option<_i3.Either<_i11.AuthError, bool>>>);
  @override
  _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>> forgotPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>.value(
            _FakeEither_2<_i11.AuthError, _i3.Unit>(
          this,
          Invocation.method(
            #forgotPassword,
            [email],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>.value(
                _FakeEither_2<_i11.AuthError, _i3.Unit>(
          this,
          Invocation.method(
            #forgotPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>);
  @override
  _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>.value(
            _FakeEither_2<_i11.AuthError, _i3.Unit>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>.value(
                _FakeEither_2<_i11.AuthError, _i3.Unit>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>);
  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>> register({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #name: name,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>.value(
            _FakeEither_2<_i11.AuthError, _i3.Unit>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #name: name,
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>.value(
                _FakeEither_2<_i11.AuthError, _i3.Unit>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #name: name,
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>);
  @override
  _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>> sendVerificationEmail() =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVerificationEmail,
          [],
        ),
        returnValue: _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>.value(
            _FakeEither_2<_i11.AuthError, _i3.Unit>(
          this,
          Invocation.method(
            #sendVerificationEmail,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>.value(
                _FakeEither_2<_i11.AuthError, _i3.Unit>(
          this,
          Invocation.method(
            #sendVerificationEmail,
            [],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i11.AuthError, _i3.Unit>>);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i12.SecureStorageService {
  @override
  _i4.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<String?> read(String? key) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
  @override
  _i4.Future<void> write({
    required String? key,
    required String? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i13.NetworkService {
  @override
  _i13.NetworkStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i13.NetworkStatus.connected,
        returnValueForMissingStub: _i13.NetworkStatus.connected,
      ) as _i13.NetworkStatus);
  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i4.Future<void> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.StreamSubscription<_i14.InternetConnectionStatus> listenForChange() =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForChange,
          [],
        ),
        returnValue: _FakeStreamSubscription_3<_i14.InternetConnectionStatus>(
          this,
          Invocation.method(
            #listenForChange,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeStreamSubscription_3<_i14.InternetConnectionStatus>(
          this,
          Invocation.method(
            #listenForChange,
            [],
          ),
        ),
      ) as _i4.StreamSubscription<_i14.InternetConnectionStatus>);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OpenMailAppService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenMailAppService extends _i1.Mock
    implements _i15.OpenMailAppService {
  @override
  _i4.Future<void> openMailApp() => (super.noSuchMethod(
        Invocation.method(
          #openMailApp,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [EventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventService extends _i1.Mock implements _i16.EventService {
  @override
  List<_i5.Event?> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: <_i5.Event?>[],
        returnValueForMissingStub: <_i5.Event?>[],
      ) as List<_i5.Event?>);
  @override
  _i4.Stream<List<_i5.Event?>> get upcomingEventsStream => (super.noSuchMethod(
        Invocation.getter(#upcomingEventsStream),
        returnValue: _i4.Stream<List<_i5.Event?>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Event?>>.empty(),
      ) as _i4.Stream<List<_i5.Event?>>);
  @override
  _i4.Stream<_i5.Event?> get featuredEventStream => (super.noSuchMethod(
        Invocation.getter(#featuredEventStream),
        returnValue: _i4.Stream<_i5.Event?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Event?>.empty(),
      ) as _i4.Stream<_i5.Event?>);
  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i4.Stream<List<_i5.Guest?>> guestsStream(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #guestsStream,
          [eventId],
        ),
        returnValue: _i4.Stream<List<_i5.Guest?>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Guest?>>.empty(),
      ) as _i4.Stream<List<_i5.Guest?>>);
  @override
  _i4.Stream<int> numberOfGuestsStream(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #numberOfGuestsStream,
          [eventId],
        ),
        returnValue: _i4.Stream<int>.empty(),
        returnValueForMissingStub: _i4.Stream<int>.empty(),
      ) as _i4.Stream<int>);
  @override
  _i4.Stream<_i5.Event> eventStream(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #eventStream,
          [eventId],
        ),
        returnValue: _i4.Stream<_i5.Event>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Event>.empty(),
      ) as _i4.Stream<_i5.Event>);
  @override
  _i4.Stream<bool> isAttendingStream(
    String? eventId,
    String? guestId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAttendingStream,
          [
            eventId,
            guestId,
          ],
        ),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);
  @override
  _i4.Stream<List<_i5.Event?>> myEventsStream(String? creatorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #myEventsStream,
          [creatorId],
        ),
        returnValue: _i4.Stream<List<_i5.Event?>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Event?>>.empty(),
      ) as _i4.Stream<List<_i5.Event?>>);
  @override
  _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>> addGuest(
    String? eventId,
    _i5.Guest? guest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addGuest,
          [
            eventId,
            guest,
          ],
        ),
        returnValue: _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
            _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #addGuest,
            [
              eventId,
              guest,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
                _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #addGuest,
            [
              eventId,
              guest,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>);
  @override
  _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>> removeGuest(
    String? eventId,
    String? guestId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeGuest,
          [
            eventId,
            guestId,
          ],
        ),
        returnValue: _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
            _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #removeGuest,
            [
              eventId,
              guestId,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
                _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #removeGuest,
            [
              eventId,
              guestId,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>);
  @override
  _i4.Future<List<_i5.Guest?>> allGuests(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #allGuests,
          [eventId],
        ),
        returnValue: _i4.Future<List<_i5.Guest?>>.value(<_i5.Guest?>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Guest?>>.value(<_i5.Guest?>[]),
      ) as _i4.Future<List<_i5.Guest?>>);
  @override
  _i4.Future<int> getNumberOfGuests(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getNumberOfGuests,
          [eventId],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>> createEvent(
          _i5.Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
            _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
                _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>);
  @override
  _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>> deleteEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [eventId],
        ),
        returnValue: _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
            _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #deleteEvent,
            [eventId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
                _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #deleteEvent,
            [eventId],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>);
  @override
  _i4.Future<_i3.Either<_i17.EventError, List<_i5.Event?>>> getAllEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue:
            _i4.Future<_i3.Either<_i17.EventError, List<_i5.Event?>>>.value(
                _FakeEither_2<_i17.EventError, List<_i5.Event?>>(
          this,
          Invocation.method(
            #getAllEvents,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i17.EventError, List<_i5.Event?>>>.value(
                _FakeEither_2<_i17.EventError, List<_i5.Event?>>(
          this,
          Invocation.method(
            #getAllEvents,
            [],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i17.EventError, List<_i5.Event?>>>);
  @override
  _i4.Future<_i5.Event> getEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getEvent,
          [eventId],
        ),
        returnValue: _i4.Future<_i5.Event>.value(_FakeEvent_4(
          this,
          Invocation.method(
            #getEvent,
            [eventId],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i5.Event>.value(_FakeEvent_4(
          this,
          Invocation.method(
            #getEvent,
            [eventId],
          ),
        )),
      ) as _i4.Future<_i5.Event>);
  @override
  _i4.Future<List<_i5.Event?>> getEvents() => (super.noSuchMethod(
        Invocation.method(
          #getEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Event?>>.value(<_i5.Event?>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Event?>>.value(<_i5.Event?>[]),
      ) as _i4.Future<List<_i5.Event?>>);
  @override
  _i4.Future<List<_i5.Guest?>> getEventGuests(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventGuests,
          [eventId],
        ),
        returnValue: _i4.Future<List<_i5.Guest?>>.value(<_i5.Guest?>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Guest?>>.value(<_i5.Guest?>[]),
      ) as _i4.Future<List<_i5.Guest?>>);
  @override
  _i4.Future<bool> isAttending(
    String? eventId,
    String? guestId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAttending,
          [
            eventId,
            guestId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<_i5.Event> getFeaturedEvent() => (super.noSuchMethod(
        Invocation.method(
          #getFeaturedEvent,
          [],
        ),
        returnValue: _i4.Future<_i5.Event>.value(_FakeEvent_4(
          this,
          Invocation.method(
            #getFeaturedEvent,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i5.Event>.value(_FakeEvent_4(
          this,
          Invocation.method(
            #getFeaturedEvent,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Event>);
  @override
  _i4.Future<_i3.Either<_i17.EventError, List<_i5.Event?>>> getMyEvents(
          String? creatorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyEvents,
          [creatorId],
        ),
        returnValue:
            _i4.Future<_i3.Either<_i17.EventError, List<_i5.Event?>>>.value(
                _FakeEither_2<_i17.EventError, List<_i5.Event?>>(
          this,
          Invocation.method(
            #getMyEvents,
            [creatorId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i17.EventError, List<_i5.Event?>>>.value(
                _FakeEither_2<_i17.EventError, List<_i5.Event?>>(
          this,
          Invocation.method(
            #getMyEvents,
            [creatorId],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i17.EventError, List<_i5.Event?>>>);
  @override
  _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>> removeEvent(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeEvent,
          [uid],
        ),
        returnValue: _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
            _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #removeEvent,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
                _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #removeEvent,
            [uid],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>);
  @override
  _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>> updateEvent(
          _i5.Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [event],
        ),
        returnValue: _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
            _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #updateEvent,
            [event],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>.value(
                _FakeEither_2<_i17.EventError, _i3.Unit>(
          this,
          Invocation.method(
            #updateEvent,
            [event],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i17.EventError, _i3.Unit>>);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MediaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaService extends _i1.Mock implements _i18.MediaService {
  @override
  _i6.Reference get storageRef => (super.noSuchMethod(
        Invocation.getter(#storageRef),
        returnValue: _FakeReference_5(
          this,
          Invocation.getter(#storageRef),
        ),
        returnValueForMissingStub: _FakeReference_5(
          this,
          Invocation.getter(#storageRef),
        ),
      ) as _i6.Reference);
  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  dynamic getFileFromCloud(_i6.Reference? ref) => super.noSuchMethod(
        Invocation.method(
          #getFileFromCloud,
          [ref],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<_i19.XFile?> getImage({required bool? fromGallery}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImage,
          [],
          {#fromGallery: fromGallery},
        ),
        returnValue: _i4.Future<_i19.XFile?>.value(),
        returnValueForMissingStub: _i4.Future<_i19.XFile?>.value(),
      ) as _i4.Future<_i19.XFile?>);
  @override
  _i4.Future<List<_i19.XFile>?> retrieveLostData() => (super.noSuchMethod(
        Invocation.method(
          #retrieveLostData,
          [],
        ),
        returnValue: _i4.Future<List<_i19.XFile>?>.value(),
        returnValueForMissingStub: _i4.Future<List<_i19.XFile>?>.value(),
      ) as _i4.Future<List<_i19.XFile>?>);
  @override
  _i4.Future<List<_i19.XFile>?> getMultiImages() => (super.noSuchMethod(
        Invocation.method(
          #getMultiImages,
          [],
        ),
        returnValue: _i4.Future<List<_i19.XFile>?>.value(),
        returnValueForMissingStub: _i4.Future<List<_i19.XFile>?>.value(),
      ) as _i4.Future<List<_i19.XFile>?>);
  @override
  dynamic uploadFileToCloud(
    String? path,
    String? name,
    _i6.Reference? ref,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #uploadFileToCloud,
          [
            path,
            name,
            ref,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i20.ChatService {
  @override
  _i4.Future<_i3.Either<_i21.ChatError, _i22.ChatResponse>> sendMessage(
          List<_i23.Message>? msgs) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [msgs],
        ),
        returnValue:
            _i4.Future<_i3.Either<_i21.ChatError, _i22.ChatResponse>>.value(
                _FakeEither_2<_i21.ChatError, _i22.ChatResponse>(
          this,
          Invocation.method(
            #sendMessage,
            [msgs],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i21.ChatError, _i22.ChatResponse>>.value(
                _FakeEither_2<_i21.ChatError, _i22.ChatResponse>(
          this,
          Invocation.method(
            #sendMessage,
            [msgs],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i21.ChatError, _i22.ChatResponse>>);
}
